### ISSUE TITLE
I keep getting a "No module named 'tensorflow.contrib' error

### ISSUE THREAD

**Issue by FrankGehry** [otuva/handwriting-synthesis#1]
Any idea why I would keep getting that error when trying to run demo.py?

**Comment by otuva** [comment]
@FrankGehry You are trying to run demo.py from the original repo, correct?

Can you install as per the [installation instructions](https://github.com/otuva/handwriting-synthesis#installation) and try to use it from `main.py`? It's the same as `demo.py`
